%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny_gray_threshold: 10
Canny_len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel_size: 0.5
Voxel_down_sample_size: 0.02
Plane_min_points_size: 30
Plane_normal_theta_min: 45
Plane_normal_theta_max: 135
Plane_max_size: 8
Ransac_dis_threshold: 0.02
Edge_min_dis_threshold: 0.03
Edge_max_dis_threshold: 0.06
