%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

# Lidar Data type(custom msg or pointcloud2)
Data_custom_msg: 0
# Initial extrinsic (usually provided by hand measurement or cad design)

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.0,
         0.0,  0.0,  -1.0,    0.0,
         1.0,   0.0,    0.0,    0.0,
         0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny_gray_threshold: 20
Canny_len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel_size: 1.0
Voxel_down_sample_size: 0.02
Plane_min_points_size: 60
Plane_normal_theta_min: 30
Plane_normal_theta_max: 150
Plane_max_size: 5
Ransac_dis_threshold: 0.015
Ransac_iter_num: 200
Edge_min_dis_threshold: 0.03
Edge_max_dis_threshold: 0.06

# Params for color point clouds
Color_dense: 1
Color_intensity_threshold: 10
